### ISSUE TITLE
Расширенная модель передвижения

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/code-practice#19]
Необходимо модифицировать существующую систему передвижения и добавить следующие элементы: двойной прыжок при повторном нажатии пробела в воздухе, ускорение при зажатом шифте и рывок при нажатии на букву "C".

**Comment by Wacko34** [comment]
Начал в 14:20
Сделал ускорение, сделал дэш
С двойным прыжком пока проблемы
Где-то в 17 можно считать, что закончил, потому что еще с Пашей разбирались с анимацией

**Comment by Wacko34** [comment]
забыл засечь время, но где-то час занял рефактор + исправления
