### ISSUE TITLE
Дополнительный материал

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/code-practice#20]
Необходимо прочитать/посмотреть дополнительный материал на выбор исполнителя. Результатом должен быть обновлённый README файл, содержащий ссылку на источник и полученные в результате знания/навыки.

**Comment by Wacko34** [comment]
10:50 -- начал чтение материала про порядок событий в Unity
12:45 -- закончил
Что читал:
https://habr.com/ru/articles/147315/
https://docs.unity3d.com/Manual/ExecutionOrder.html
https://docs.unity3d.com/ScriptReference/MonoBehaviour.html и описания его методов
