### ISSUE TITLE
Фиксы багов

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/code-practice#23]
Необходимо пофиксить передвижение персонажа, котороая перерастает в его полет по всей карте. Анимация также должна четко соотвествовать текущему состоянию. Фиксы иных багов также приветсвтуются, главное заносить их описание и метод исправления в комментарии.

**Comment by Wacko34** [comment]
@HozzyUwU 
Был баг с тем, что персонаж дэшился все время в разные стороны из-за:
```
_dashForce = m_FacingRight ? 1 : -1;
```

Пофиксил добавлением переменной:
```
float direction = m_FacingRight ? 1 : -1;
```

**Comment by Wacko34** [comment]
@HozzyUwU 
Баг с прыжком пофиксил костылем:
Баг был из-за того, что персонаж мог приземлиться только тогда, когда он сделал два прыжка. Добавил возможность "приземлиться", если был сделан хотя бы один прыжок:
```
	if (_countOfJumps < _maxCountOfJump)
	{
		wasGrounded = false; 
	}
```

**Comment by HozzyUwU** [comment]
Необходимо поместить графику на один уровень с коллайдером

![Image](https://github.com/PAD1K/code-practice/assets/82671681/c40740b2-c166-419f-bb19-fc6c812eb09c)

**Comment by HozzyUwU** [comment]
Необходимо убрать полет после подъема по наклонной поверхности



![Image](https://github.com/PAD1K/code-practice/assets/82671681/45e3346e-041c-49c8-902d-7e0c57ab6e5d)

**Comment by HozzyUwU** [comment]
Необходимо убрать возможность зависнуть в воздухе при нажатии движения в сторону стены в процессе прыжка



![Image](https://github.com/PAD1K/code-practice/assets/82671681/27a38a93-5b42-48d0-b636-f169f6695575)

**Comment by Wacko34** [comment]
> Необходимо поместить графику на один уровень с коллайдером

Пофиксил изменением координаты коллайдеров:
1. В Awake() запоминаю начальные координаты
2. При прыжке добавляю к этим координатам _jumpForce по оси Y
3. При приземлении возвращаю старые координаты.

**Comment by Wacko34** [comment]
> Необходимо убрать полет после подъема по наклонной поверхности

Ну пока есть предположения, что дело в нормалях

Посмотрел этот  видос https://www.youtube.com/watch?v=puPjNRJMmOc буду пробовать переделать

**Comment by Wacko34** [comment]
@HozzyUwU 
Пока нет продвижения. Пробовал разные способы -- не помогает. Где-то не работает физика, где-то отваливаются костыли. 
Завтра буду пробовать еще.
Моя основная идея: использовать скорость только вдоль проекции на плоскость с которой взаимодействует объетк.

Завтра буду смотреть:
https://www.youtube.com/watch?v=QPiZSTEuZnw
https://www.reddit.com/r/Unity2D/comments/couwco/how_do_i_keep_the_player_from_flying_off_of_slopes/?rdt=61942
