### ISSUE TITLE
Реализация боевой системы

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/code-practice#27]
Необходимо добавить возможность наносить удар по противникам. Соотвественно стоит сделать модель монеты нашим противником. Для реализации функционала стоит использовать следующий [видеоурок](https://www.youtube.com/watch?v=sPiVz1k-fEs&list=PLPV2KyIb3jR6TFcFuzI2bB7TMNIIBpKMQ&index=9).

**Comment by Wacko34** [comment]
@HozzyUwU 
Посмотрел видос 
Начал работу над задачей в 10:10

**Comment by Wacko34** [comment]
@HozzyUwU 
Сделал боевку, но пока без анимаций получения урона и смерти монеты. Сделал просто ее отключение.

**Comment by Wacko34** [comment]
@HozzyUwU 
Нашел баг, что если ударить в воздухе, то анимация выполнится при приземлении. Пофиксил тем, что сделал установку триггера, если персонаж не в прыжке.
