### ISSUE TITLE
Добавление пользовательского интерфейса

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/code-practice#29]
Необходимо создать базовый графический интерфейс для отображения следующих элементов: здоровье игрока, стамина игрока (стоит также ее связать с ударами противника), счетчик опыта. Для реализации элементов стоит ознакомиться с [канвасом](https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/index.html).

**Comment by Wacko34** [comment]
Начал работу, пока читаю доку

**Comment by Wacko34** [comment]
Начал в 16:40
Сделал отображение ХП пингвина.
Были проблемы с появлением красного креста, когда значение заливки становилось равным нулю. Решил тем, что удалил и заново создал заливку.

Сделал отображение и работу стамины.
Стамина тратится при беге если нажимать на шифт и находиться в движени.
При дэше тратится 10 стамины, если она больше 10.
Стамина восстанавливается если отжат шифт.
При атаке тратится 20 стамины, если она больше 20.

Реализовал опыт:
При убийстве монеты ищется компонент ГГ через
```
GameObject player = GameObject.Find("Player"); // не знаю насколько это правильно
```
и в слайдер добавляется одно очко. Как только опыт достигает максимального значения, то значение слайдера сбрасывается до нуля, а счетчик уровня (нигде не отображается) ГГ увеличивается на 1.

**Comment by Wacko34** [comment]
@HozzyUwU Можно проверять
