### ISSUE TITLE
Обнови меня 🐖

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/code-practice#30]
Необходимо обновить версию Unity до 2022.3.17f1.

**Comment by Wacko34** [comment]
![Image](https://github.com/PAD1K/code-practice/assets/80835973/8def3664-1a44-4eff-bbee-5f346e7bc375)

**Comment by LadygaPavel** [comment]
хрю

**Comment by Wacko34** [comment]
@HozzyUwU 
Пруф


![Image](https://github.com/PAD1K/code-practice/assets/80835973/8c69720f-b491-438e-8938-e6bf6660aeeb)
