### ISSUE TITLE
Ускоренное падение при касании угла

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/code-practice#33]
Необходимо исправить баг, при котором персонаж с повышенной скоростью опускается резко вниз, если в течении прыжка касается наклонной поверхности.

https://github.com/PAD1K/code-practice/assets/82671681/50ec0d3f-580c-4829-b988-50bc20ea0953

**Comment by Wacko34** [comment]
@HozzyUwU 
Пробовал убрать действие силы. если игрок не касается земли прямо под собой:
```
RaycastHit2D hit = Physics2D.Raycast(transform.position, Vector3.down, 3f, _groundLayer);
```
Не получилось. Идей больше нет

**Comment by Wacko34** [comment]
@HozzyUwU 
Оставил так, можно проверять
