### ISSUE TITLE
Группировка элементов

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/code-practice#34]
Нет повода дублировать несколько канвасов в сцене, стоит добавить в один из канвасов панель и на ней расположить элементы другого канваса. Также для организации тематические элементы должны находится в одной группе, например, создать емпти "Enemies" и привязать к нему всех врагов.

![Image](https://github.com/PAD1K/code-practice/assets/82671681/75c8a035-ea85-4e6e-89f9-f8161fc99c4b)

**Comment by Wacko34** [comment]
@HozzyUwU 
Почему сделал два канваса:
не разобрался как сделать так, чтобы фон был в самом низу, а статистики в самом верху. Сейчас нагуглил, что нужно было добавить компонент Canvas для разных элементов канваса
