### ISSUE TITLE
Адаптация канваса под разрешение экрана

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/code-practice#35]
Необходимо поработать с Canvas Scaler и Anchor's  на элементах внутри канваса, чтобы при изменение разрешения экрана лейаут оставался пержним.

**Comment by Wacko34** [comment]
@HozzyUwU 
Сделал привязку статистик к левому углу. 

Предисловие: параметры экрана для рендера выбрал 4к, но также смотрел на других.

Canvas Scaler выставил "Scale with screen size":
![Image](https://github.com/PAD1K/code-practice/assets/80835973/fb857081-1d9e-497f-8c96-ff74f583f65b)

Для примера "Constant scale size":
![Image](https://github.com/PAD1K/code-practice/assets/80835973/e2333831-a192-4adc-ae6b-2fbe6df106b1)

"Constant physycal size":
![Image](https://github.com/PAD1K/code-practice/assets/80835973/c17bd727-29f9-4ca0-8f9f-fa4418c7a182)
